# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 87cb28da292bea5ba553b3aa47f5b58a535e7204bfd0f9972f1376c9e6544e7c6914452b32ab0420c858e1eda61186a064339c6a7346d1b127e841d703dab092

test:
  secret_key_base: 53b6e14fc0d5c1b83f98dc271a0137929a7a89386bdd66e018adef689be376de8a7d7fa8b87e50fe7ed7a1f12f9b6cc409b69ce748d50357c5bc4c8e2f189beb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
